name: Build Debug APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        id: check_tag
        run: echo "${{ github.ref_name }}"

      - name: Check Tag Prefix
        id: check_tag_prefix
        run: | 
          if [[ "${{ steps.check_tag.outputs.check_tag }}" == v* ]]; then
            echo "Tag starts with 'v', continue with the workflow"
          else
            echo "Tag does not start with 'v', existing workflow"
            exit 1
          fi
      - name: Echo Hello world
        run: echo "Hello world"

  build:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build Debug Apk
        run: ./gradlew assembleDebug

