name: Reusable workflow for tag Validation

on: workflow_call

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        id: check_tag
        run: echo "${{ github.ref_name }}"
      - name: Check Tag Prefix
        id: check_tag_prefix
        run: |
          if [[ "${{ steps.check_tag.outputs.check_tag }}" == v* ]]; then
            echo "Tag starts with 'v', continue with the workflow"
          else
            echo "Tag does not start with 'v', existing workflow"
            exit 1
          fi


