name: Build Debug APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  validate_tag:
    uses: ./.github/workflows/tag_validation.yml

  build:
    needs: validate_tag
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Build Debug Apk
        run: ./gradlew assembleDebug
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

